### ISSUE TITLE
GPU Simulation Optimizations

### ISSUE THREAD

**Issue by CapdinCrando** [jhunterh/Mancala-GPU-Project#17]
1. Try experimenting with the EXPLORATION variable. It should be lower for the GPU version. Maybe it would be possible to calculate this value from something else, like say the iteration count or win states desired from multi?
2. Implement using multiple blocks instead of 1 block. It may be worth using the launch configurator, and potentially a variable win states desired based on the block and grid size.

**Comment by CapdinCrando** [comment]
Another idea would be to enforce more thread syncing, which may help, idk.

**Comment by jhunterh** [comment]
Treating this as GPU optimization 1. There can and will likely be more issues opened for further optimization.
