### ISSUE TITLE
Mancala Game Implementation - Game End State Bug

### ISSUE THREAD

**Issue by jhunterh** [jhunterh/Mancala-GPU-Project#4]
During development for the Monte Carlo Single Threaded Implementation:
An issue with the Mancala end-state detection logic was noticed.
Currently, the board checks to see if a player is out of moves by seeing if their side has no stones in it.
However, the game is not over unless that player has no stones on their side AND it is their turn.
In the screenshot attached, Player 1 makes move 1. The state of Player 1's side of the board should then be 8 0 1 1 0 0, but is instead 8 0 0 1 0 0. It seems like the logic for detecting a steal does not check for the opponents side to be 0.
<img width="431" alt="issue" src="https://user-images.githubusercontent.com/44873307/219971631-c330c430-c224-4262-9506-9289757fc386.png">

**Comment by CapdinCrando** [comment]
This was originally intentional, due to my lack of understanding of Mancala. I thought it was that if any player had no pieces left on their side. I shall work on the fix.
